#!/usr/bin/env bash
# Build web-optimized assets from _assets_src/<project>/ (originals, gitignored)
# into assets/<project>/ (committed). Drop files into a project folder and re-run.
#
# Role is decided by WHERE a file sits inside the project folder:
#   _assets_src/<proj>/hero/    -> ON THE BOARD, biggest   (the one standout)
#   _assets_src/<proj>/board/   -> ON THE BOARD            (supporting)
#   _assets_src/<proj>/<loose>  -> GALLERY-ONLY            (the default — anything sitting loose)
#   _assets_src/<proj>/archive/ -> IGNORED                 (cut; not built)
# Output is FLAT — the role subfolder is stripped, so paths never change:
#   assets/<proj>/<name>.webp | .mp4
# assets/board-manifest.js lists EVERY built file (order hero→board→gallery, with kind & role);
# concept.html renders the galleries straight from it, so a file dropped into _assets_src just shows up.
#
#   images (png/jpg/jpeg/tif/heic/webp) -> .webp  (max width 1500, q82, no upscale)
#   gif/mov/mp4/m4v                     -> .mp4   (muted autoplay loop, max width 960)
# Requires: cwebp, ffmpeg, sips (macOS).
set -euo pipefail
cd "$(dirname "$0")"
SRC=_assets_src
OUT=assets
IMG_W=1500; IMG_Q=82; VID_W=960
rm -rf "$OUT"

# transcode one source file into a project's output dir (flat — role subfolder dropped)
process_file(){
  local f="$1" outdir="$2"
  [ -f "$f" ] || return 0
  local base name ext; base=$(basename "$f"); name="${base%.*}"; ext="${base##*.}"
  [ "$base" = ".DS_Store" ] && return 0
  shopt -s nocasematch
  case "$ext" in
    png|jpg|jpeg|tif|tiff|heic|webp)
      local w; w=$(sips -g pixelWidth "$f" 2>/dev/null | awk '/pixelWidth/{print $2}')
      if [ -n "$w" ] && [ "$w" -gt "$IMG_W" ]; then
        cwebp -quiet -q "$IMG_Q" -resize "$IMG_W" 0 "$f" -o "$outdir/$name.webp"
      else
        cwebp -quiet -q "$IMG_Q" "$f" -o "$outdir/$name.webp"
      fi ;;
    gif|mov|mp4|m4v)
      ffmpeg -y -loglevel error -i "$f" -movflags +faststart -pix_fmt yuv420p -an \
        -vf "scale='min($VID_W,iw)':-2:flags=lanczos" -crf 30 "$outdir/$name.mp4" ;;
    *) echo "skip $f" ;;
  esac
  shopt -u nocasematch
}

# echo a manifest entry  {"f":base,"k":i|v,"r":role}  for a file
entry_json(){
  local base ext k; base=$(basename "$1"); ext="${base##*.}"; base="${base%.*}"
  shopt -s nocasematch; case "$ext" in gif|mov|mp4|m4v) k=v;; *) k=i;; esac; shopt -u nocasematch
  printf '{"f":"%s","k":"%s","r":"%s"}' "$base" "$k" "$2"
}

shopt -s nullglob nocaseglob
mkdir -p "$OUT"
GAL_BODY=""

for dir in "$SRC"/*/; do
  proj=$(basename "$dir")
  mkdir -p "$OUT/$proj"
  ent=""; hc=0; bc=0; gc=0
  add_ent(){ if [ -z "$ent" ]; then ent="$1"; else ent="$ent,$1"; fi; }

  for f in "$dir"hero/*; do
    [ -f "$f" ] || continue; [ "$(basename "$f")" = ".DS_Store" ] && continue
    process_file "$f" "$OUT/$proj"; add_ent "$(entry_json "$f" hero)"; hc=$((hc+1)); done
  for f in "$dir"board/*; do
    [ -f "$f" ] || continue; [ "$(basename "$f")" = ".DS_Store" ] && continue
    process_file "$f" "$OUT/$proj"; add_ent "$(entry_json "$f" board)"; bc=$((bc+1)); done
  for f in "$dir"*; do
    [ -f "$f" ] || continue; [ "$(basename "$f")" = ".DS_Store" ] && continue
    process_file "$f" "$OUT/$proj"; add_ent "$(entry_json "$f" gallery)"; gc=$((gc+1)); done

  if [ -z "$GAL_BODY" ]; then GAL_BODY="\"$proj\":[$ent]"; else GAL_BODY="$GAL_BODY,\"$proj\":[$ent]"; fi
  echo "  $proj: $hc hero + $bc board · $gc gallery"
done

MANIFEST="$OUT/board-manifest.js"
{
  echo "/* generated by build-assets.sh — every built file per project (order hero→board→gallery) */"
  echo "window.GALLERY={$GAL_BODY};"
} > "$MANIFEST"
echo "── assets/ built · board-manifest.js written ──"
echo "total: $(du -sh "$OUT" | cut -f1)"
